name: "FPP - Falcon Player"
description: "Falcon Player (FPP) is a lightweight, optimized, feature-rich sequence player"
version: "master"
slug: "app-fpp"
url: "https://github.com/jessica12ryan/homesync-ha-apps"

image: "falconchristmas/fpp"

arch:
  - amd64
  - aarch64
  - armhf
  
startup: "services"
boot: "auto"

host_network: true
host_ipc: true

full_access: true

ingress: true
ingress_port: 80
panel_icon: mdi:led-strip-variant

map:
  - config:rw

environment:
  FPP_MEDIA_DIR: /home/fpp/media
